<template>
  <div class="detail_box">
    <h2 class="label-tit-20">시간대별 학습비율</h2>
    <table class="detail_table mt14">
    <thead>
        <tr>
            <td>구간</td>
            <td>편수</td>
            <td>인원</td>
            <td>시간</td>
            <td>비율</td>
        </tr>
    </thead>
    <tbody>
        <tr>
            <td>0~1시간</td>
            <td>323</td>
            <td>323</td>
            <td>1000</td>
            <td>29.3%</td>
        </tr>
        <tr>
            <td>1~10시간</td>
            <td>321</td>
            <td>323</td>
            <td>1000</td>
            <td>29.3%</td>
        </tr>
        <tr>
            <td>10~20시간</td>
            <td>2</td>
            <td>2</td>
            <td>200</td>
            <td>10.3%</td>
        </tr>
        <tr>
            <td>20~30시간</td>
            <td>0</td>
            <td>2</td>
            <td>200</td>
            <td>10.3%</td>
        </tr>
        <tr>
            <td>30시간 이상</td>
            <td>114</td>
            <td>0</td>
            <td>600</td>
            <td>20.0%</td>
        </tr>
        <tr>
            <td>합계</td>
            <td>1,024</td>
            <td>1,024</td>
            <td>3000</td>
            <td>100%</td>
        </tr>
    </tbody>
    </table>
    <p class="hr" style="margin-top:26px; margin-bottom:22px;"></p>
    <h2 class="label-tit-20">CP사별 학습현황</h2>
    <table class="detail_table mt14">
    <thead>
        <tr>
            <td>구간</td>
            <td>편수</td>
            <td>인원</td>
            <td>시간</td>
            <td>비율</td>
        </tr>
    </thead>
    <tbody>
        <tr>
            <td>멀티캠퍼스</td>
            <td>323</td>
            <td>323</td>
            <td>4:20:17</td>
            <td>29.3%</td>
        </tr>
        <tr>
            <td>현대백화점그룹</td>
            <td>321</td>
            <td>323</td>
            <td>4:20:17</td>
            <td>29.3%</td>
        </tr>
        <tr>
            <td>Lynda</td>
            <td>2</td>
            <td>2</td>
            <td>4:20:17</td>
            <td>10.3%</td>
        </tr>
        <tr>
            <td>합계</td>
            <td>1,024</td>
            <td>1,024</td>
            <td>34:20:17</td>
            <td>100%</td>
        </tr>
    </tbody>
    </table>
    <p class="hr" style="margin-top:26px; margin-bottom:22px;"></p>
    <h2 class="label-tit-20">분류별 세부학습현황</h2>
    <table class="detail_table mt14">
    <thead>
        <tr>
            <td>분류명</td>
            <td>편수</td>
            <td>인원</td>
            <td>시간</td>
            <td>비율</td>
        </tr>
    </thead>
    <tbody>
        <tr>
            <td>경영.리더십</td>
            <td>323</td>
            <td>323</td>
            <td>4:20:17</td>
            <td>29.3%</td>
        </tr>
        <tr>
            <td>외국어</td>
            <td>321</td>
            <td>323</td>
            <td>4:20:17</td>
            <td>29.3%</td>
        </tr>
        <tr>
            <td>OA</td>
            <td>2</td>
            <td>2</td>
            <td>4:20:17</td>
            <td>10.3%</td>
        </tr>
        <tr>
            <td>직무</td>
            <td>0</td>
            <td>2</td>
            <td>34:20:17</td>
            <td>10.3%</td>
        </tr>
        <tr>
            <td>인문</td>
            <td>114</td>
            <td>0</td>
            <td>600</td>
            <td>20.0%</td>
        </tr>
        <tr>
            <td>합계</td>
            <td>1,024</td>
            <td>1,024</td>
            <td>3000</td>
            <td>100%</td>
        </tr>
    </tbody>
    </table>
  </div>
</template>

<script>
export default {

}
</script>
